### ISSUE TITLE
Cannot setup OAuth key

### ISSUE THREAD

**Issue by amosbird** [yandexmobile/appmetrica-funnels#4]
Hi, I'm trying to test this in my local machine. I followed the tutorial, generated an OAuth key and an application id. After filling them into `TOKEN` and `API_KEYS` I got 
```
web_1         | Exception in thread Thread-1:
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
web_1         |     self.run()
web_1         |   File "/usr/local/lib/python2.7/threading.py", line 754, in run
web_1         |     self.__target(*self.__args, **self.__kwargs)
web_1         |   File "./run.py", line 35, in update_loop
web_1         |     updater(first_flag=True)
web_1         |   File "/usr/src/logs_api_int_script.py", line 265, in main
web_1         |     process_date(date_str, token, api_key, CH_DATABASE, CH_TABLE)
web_1         |   File "/usr/src/logs_api_int_script.py", line 203, in process_date
web_1         |     raise ValueError, r.text
web_1         | ValueError: Don't have rights for this
```

Is there a more elaborate tutorial for this? Or is there a sample database that I can test directly? Thanks.

**Comment by bamx23** [comment]
Do you use docker-compose or start with docker commands? Does your account (of the token) have access to the app with that id? Looks like there is something wrong with the token.

**Comment by amosbird** [comment]
> Do you use docker-compose or start with docker commands?

I used docker-compose command. 

> Does your account (of the token) have access to the app with that id?

Um, I'm not sure. How can I test that?

**Comment by bamx23** [comment]
You've generated OAuth token for some account by opening URL as it described here: https://tech.yandex.com/oauth/doc/dg/reference/console-client-docpage/
And also your OAuth application should request access for reading AppMetrica data.

**Comment by amosbird** [comment]
I don't get it. This is the client I've created 
![image](https://user-images.githubusercontent.com/5085485/31624092-1e6e7190-b267-11e7-90d7-cbfc49f045a3.png)

and this appmetrica application

![image](https://user-images.githubusercontent.com/5085485/31624152-53d58a30-b267-11e7-88fb-fd57d3909980.png)

What else should i do then?

**Comment by bamx23** [comment]
You need to generate OAuth token for this client (it's not an ID or a password from your screenshot). Also, `API_KEYS` should be `["962757"]`.

**Comment by amosbird** [comment]
> You need to generate OAuth token for this client 

Oh, ok. But I don't find the place to generate this...

**Comment by bamx23** [comment]
Open this URL(use your client ID):
`https://oauth.yandex.com/authorize?response_type=token&client_id=<application ID>`
from here: https://tech.yandex.com/oauth/doc/dg/tasks/get-oauth-token-docpage/

**Comment by amosbird** [comment]
Thanks! I'm making progress now
![image](https://user-images.githubusercontent.com/5085485/31652093-9b7968c6-b2e3-11e7-8acd-7713c40e08bf.png)

So what callback url should I setup?

**Comment by bamx23** [comment]
See this page: https://tech.yandex.com/oauth/doc/dg/tasks/register-client-docpage/
You should have been clicked `Set URL for development` when you were creating a client.

**Comment by amosbird** [comment]
Thanks!
